version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gen_postgres
    environment:
      POSTGRES_DB: gen
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
  postgres_data:
